export enum actionTypes {
   JOKE_LOADING = "JOKE_LOADING",
   JOKE_SUCCESS = "JOKE_SUCCESS",
   JOKE_FAIL = "JOKE_FAIL",
   SHOW_PUNCHLINE = "SHOW_PUNCHLINE",
   HIDE_PUNCHLINE = "HIDE_PUNCHLINE",
}
